BEGIN
  -- DBC_SQL_ARCHIVE_V1: Select AI call candidates only, not bind values or responses.
  MERGE INTO DBC_SQL_CACHE_ARCHIVE a
  USING (
    SELECT RAWTOHEX(STANDARD_HASH(
             SYS_CONTEXT('USERENV','INSTANCE') || ':' || TO_CHAR(s.CON_ID) || ':' ||
             s.SQL_ID || ':' || TO_CHAR(s.CHILD_NUMBER) || ':' || RAWTOHEX(s.CHILD_ADDRESS) || ':' ||
             s.FIRST_LOAD_TIME || ':' || s.LAST_LOAD_TIME, 'SHA256')) CURSOR_KEY,
           TO_NUMBER(SYS_CONTEXT('USERENV','INSTANCE')) INSTANCE_ID,
           s.CON_ID, s.SQL_ID, s.CHILD_NUMBER, RAWTOHEX(s.CHILD_ADDRESS) CHILD_ADDRESS,
           s.FIRST_LOAD_TIME, s.LAST_LOAD_TIME, s.PARSING_SCHEMA_NAME,
           s.SQL_FULLTEXT, s.SQL_TEXT SQL_PREVIEW, s.LAST_ACTIVE_TIME,
           s.EXECUTIONS, s.ELAPSED_TIME, s.CPU_TIME, s.BUFFER_GETS, s.DISK_READS,
           s.ROWS_PROCESSED, s.MODULE, s.ACTION, s.PLAN_HASH_VALUE
    FROM SYS.V_$SQL s
    WHERE s.PARSING_SCHEMA_NAME = SYS_CONTEXT('USERENV','SESSION_USER')
      AND INSTR(s.SQL_TEXT, 'DBC_SQL_ARCHIVE_V1') = 0
      -- Filter before MERGE. Ignore ordinary literals/comments when identifying calls.
      AND REGEXP_LIKE(
        REGEXP_REPLACE(s.SQL_FULLTEXT,
          q'~[qQ]'\[([^]]|]+[^]'])*]+'|[qQ]'\{([^}]|}+[^}'])*}+'|[qQ]'<([^>]|>+[^>'])*>+'|[qQ]'\(([^)]|\)+[^)'])*\)+'|'(''|[^'])*'|--[^
]*|/\*([^*]|\*+[^*/])*\*+/~', ' ', 1, 0, 'n'),
        '(^[[:space:]]*select[[:space:]]+ai([[:space:]]|$))|((^|[^[:alnum:]_$#])"?DBMS_CLOUD_AI"?[[:space:]]*[.][[:space:]]*"?GENERATE"?[[:space:]]*[(])',
        'i')
  ) s ON (a.CURSOR_KEY = s.CURSOR_KEY)
  WHEN MATCHED THEN UPDATE SET
    a.LAST_SEEN = SYSTIMESTAMP, a.LAST_ACTIVE_TIME = s.LAST_ACTIVE_TIME,
    a.EXECUTIONS = s.EXECUTIONS, a.ELAPSED_TIME = s.ELAPSED_TIME,
    a.CPU_TIME = s.CPU_TIME, a.BUFFER_GETS = s.BUFFER_GETS,
    a.DISK_READS = s.DISK_READS, a.ROWS_PROCESSED = s.ROWS_PROCESSED,
    a.MODULE = s.MODULE, a.ACTION = s.ACTION, a.PLAN_HASH_VALUE = s.PLAN_HASH_VALUE
  WHEN NOT MATCHED THEN INSERT (
    CURSOR_KEY, INSTANCE_ID, CON_ID, SQL_ID, CHILD_NUMBER, CHILD_ADDRESS,
    FIRST_LOAD_TIME, LAST_LOAD_TIME, PARSING_SCHEMA_NAME, SQL_FULLTEXT, SQL_PREVIEW,
    FIRST_SEEN, LAST_SEEN, LAST_ACTIVE_TIME, EXECUTIONS, ELAPSED_TIME, CPU_TIME,
    BUFFER_GETS, DISK_READS, ROWS_PROCESSED, MODULE, ACTION, PLAN_HASH_VALUE
  ) VALUES (
    s.CURSOR_KEY, s.INSTANCE_ID, s.CON_ID, s.SQL_ID, s.CHILD_NUMBER, s.CHILD_ADDRESS,
    s.FIRST_LOAD_TIME, s.LAST_LOAD_TIME, s.PARSING_SCHEMA_NAME, s.SQL_FULLTEXT, s.SQL_PREVIEW,
    SYSTIMESTAMP, SYSTIMESTAMP, s.LAST_ACTIVE_TIME, s.EXECUTIONS, s.ELAPSED_TIME, s.CPU_TIME,
    s.BUFFER_GETS, s.DISK_READS, s.ROWS_PROCESSED, s.MODULE, s.ACTION, s.PLAN_HASH_VALUE
  );
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
