package com.dbcompanion.service;

import com.dbcompanion.model.Ontology.*;
import java.nio.charset.StandardCharsets;
import java.text.Normalizer;
import java.util.*;

/** Catalog metadata only. Identifiers and Turtle syntax are generated by code, never by an LLM. */
public final class OntologyRdf {
    private OntologyRdf(){}
    public record Term(String kind,String value){}
    public record Triple(String subject,String predicate,Term object){}
    public record Export(String text,String documentIri,String versionIri,String tableIri,
                         Map<String,String> prefixes,List<Triple> triples){
        public Export {prefixes=Collections.unmodifiableMap(new LinkedHashMap<>(prefixes));triples=List.copyOf(triples);}
    }
    private static final Map<String,String> PREFIXES;
    static {
        var values=new LinkedHashMap<String,String>();
        values.put("dbc","urn:dbcompanion:ontology:");
        values.put("rdf","http://www.w3.org/1999/02/22-rdf-syntax-ns#");
        values.put("rdfs","http://www.w3.org/2000/01/rdf-schema#");
        values.put("skos","http://www.w3.org/2004/02/skos/core#");
        PREFIXES=Collections.unmodifiableMap(values);
    }
    public static String literal(String value){
        var out=new StringBuilder("\"");Objects.toString(value,"").codePoints().forEach(c->{
            switch(c){case '"'->out.append("\\\"");case '\\'->out.append("\\\\");case '\n'->out.append("\\n");case '\r'->out.append("\\r");case '\t'->out.append("\\t");default->{if(c>=0xD800&&c<=0xDFFF)throw new Failure(409,"mismatch");if(c<32)out.append(String.format("\\u%04X",c));else out.appendCodePoint(c);}}
        });return out.append('"').toString();
    }
    public static String part(String value){var out=new StringBuilder();for(byte b:value.getBytes(StandardCharsets.UTF_8)){int v=b&255;if(v>='A'&&v<='Z'||v>='a'&&v<='z'||v>='0'&&v<='9'||v=='_'||v=='-'||v=='.')out.append((char)v);else out.append(String.format("%%%02X",v));}return out.toString();}
    private static String expand(String fixedName){
        int colon=fixedName.indexOf(':');String namespace=PREFIXES.get(fixedName.substring(0,colon));
        if(namespace==null)throw new IllegalArgumentException("Unknown fixed RDF prefix");
        return namespace+fixedName.substring(colon+1);
    }
    /** The display and download share one typed graph; no regex-based Turtle parsing. */
    private static final class Graph {
        private final List<Triple> triples=new ArrayList<>();
        private final StringBuilder turtle=new StringBuilder();
        private boolean vocabulary;
        Graph(){PREFIXES.forEach((prefix,iri)->turtle.append("@prefix ").append(prefix).append(": <").append(iri).append("> .\n"));turtle.append('\n');}
        void add(String s,String p,Term object,String serialized){
            triples.add(new Triple(s,expand(p),object));
            turtle.append('<').append(s).append("> ").append(p).append(' ').append(serialized).append(" .\n");
        }
        void iri(String s,String p,String iri){add(s,p,new Term("IRI",iri),"<"+iri+">");}
        void type(String s,String fixedType){add(s,"rdf:type",new Term("IRI",expand(fixedType)),fixedType);}
        void value(String s,String p,String value){if(value!=null&&!value.isEmpty())add(s,p,new Term("LITERAL",value),literal(value));}
        void integer(String s,String p,int value){add(s,p,new Term("INTEGER",Integer.toString(value)),Integer.toString(value));}
        void concept(String resource,String version,String state,String preferred,List<String> aliases,String definition){
            String name=lexical(preferred);if(name.isEmpty())return;
            String scheme=version+"/vocabulary",concept=resource+"/concept";
            if(!vocabulary){type(scheme,"skos:ConceptScheme");iri(version,"dbc:vocabulary",scheme);value(scheme,"dbc:state",state);vocabulary=true;}
            iri(resource,"dbc:concept",concept);type(concept,"skos:Concept");iri(concept,"skos:inScheme",scheme);
            value(concept,"skos:prefLabel",name);value(concept,"skos:definition",definition);value(concept,"dbc:state",state);
            var seen=new HashSet<String>();seen.add(name);
            for(String alias:aliases){String term=lexical(alias);if(!term.isEmpty()&&seen.add(term))value(concept,"skos:altLabel",term);}
        }
    }
    private static String lexical(String value){return Normalizer.normalize(Objects.toString(value,"").strip(),Normalizer.Form.NFC);}
    public static String render(Entry entry){return export(entry).text();}
    public static Export export(Entry entry){
        // Preserve existing identifiers; a renderer upgrade must not rename saved resources.
        if(entry.revision()<1)throw new Failure(400,"invalid");
        try{if(!UUID.fromString(entry.documentId()).toString().equals(entry.documentId()))throw new IllegalArgumentException();}
        catch(RuntimeException ex){throw new Failure(409,"mismatch");}
        var source=entry.document().source();var meaning=entry.document().meaning();
        String document="urn:uuid:"+entry.documentId(),version=document+"/revision/"+entry.revision(),root=version+"/table";
        var g=new Graph();
        g.type(document,"dbc:CatalogDocument");g.iri(document,"dbc:revision",version);
        g.type(version,"dbc:MetadataRevision");g.iri(version,"dbc:describes",root);g.value(version,"dbc:state",entry.state());g.value(version,"dbc:actor",entry.actor());g.value(version,"dbc:recordedAt",entry.recordedAt());g.value(version,"dbc:origin",entry.document().origin());g.value(version,"dbc:profile",entry.document().profile());
        g.type(root,"dbc:TableMetadata");g.value(root,"dbc:database",source.database());g.value(root,"dbc:schema",source.schema());g.value(root,"dbc:name",source.table());g.value(root,"dbc:sourceComment",source.comment());g.value(root,"dbc:businessConcept",meaning.concept());g.value(root,"rdfs:comment",meaning.description());g.value(root,"dbc:capturedAt",source.capturedAt());
        g.concept(root,version,entry.state(),meaning.concept(),List.of(),meaning.description());
        for(var binding:meaning.valueMappings()){
            String id=root+"/value/"+part(binding.id());g.iri(root,"dbc:valueMapping",id);g.type(id,"dbc:ValueMapping");
            g.iri(id,"dbc:column",root+"/column/"+part(binding.column()));g.value(id,"dbc:operator","EQ");
            g.value(id,"dbc:valueType",binding.type());g.value(id,"rdf:value",binding.value());
            g.value(id,"dbc:name",binding.column()+" = "+binding.value());g.value(id,"dbc:origin","USER_DECLARED");
            g.concept(id,version,entry.state(),binding.label(),binding.aliases(),binding.description());
            g.value(id+"/concept","skos:notation",binding.value());
        }
        for(var c:source.columns()){
            String id=root+"/column/"+part(c.name());g.iri(root,"dbc:column",id);g.type(id,"dbc:ColumnMetadata");g.value(id,"dbc:name",c.name());g.value(id,"dbc:dataType",c.dataType());g.value(id,"dbc:nullable",c.nullable());g.value(id,"dbc:sourceComment",c.comment());g.value(id,"rdfs:comment",meaning.columns().get(c.name()).description());g.value(id,"dbc:sensitivity",meaning.columns().get(c.name()).sensitivity());
            var definition=meaning.columns().get(c.name()).definition();
            if(definition!=null){
                g.value(id,"rdfs:label",definition.label());definition.aliases().forEach(alias->g.value(id,"dbc:alias",alias));
                g.concept(id,version,entry.state(),definition.label(),definition.aliases(),meaning.columns().get(c.name()).description());
                g.value(id,"dbc:unit",definition.unit());g.value(id,"dbc:role",definition.role());
                g.value(id,"dbc:valueMeaning",definition.valueMeaning());
                g.value(id,"dbc:usageGuidance",definition.usageGuidance());
                if(!definition.labelColumn().isEmpty()&&source.columns().stream().anyMatch(label->label.name().equals(definition.labelColumn())))
                    g.iri(id,"dbc:labelColumn",root+"/column/"+part(definition.labelColumn()));
                if(!definition.profile().isBlank()){
                String review=id+"/review";g.iri(id,"dbc:review",review);g.type(review,"dbc:DefinitionReview");
                g.value(review,"dbc:assessment",definition.assessment());g.value(review,"dbc:reason",definition.reason());
                g.value(review,"dbc:uncertainty",definition.uncertainty());g.value(review,"dbc:profile",definition.profile());
                g.value(review,"dbc:sampledAt",definition.sampledAt());g.integer(review,"dbc:sampleRows",definition.sampleRows());
                g.value(review,"dbc:state",entry.state());
                }
            }
        }
        for(var k:source.keys()){
            String id=root+"/key/"+part(k.name());g.iri(root,"dbc:key",id);g.type(id,k.type().equals("R")?"dbc:ForeignKeyMetadata":"dbc:KeyMetadata");
            g.value(id,"dbc:name",k.name());g.value(id,"dbc:keyType",k.type());g.value(id,"dbc:constraintStatus",k.status());g.value(id,"dbc:validated",k.validated());g.value(id,"dbc:evidence","DATABASE_CONSTRAINT");
            g.value(id,"dbc:targetOwner",k.targetOwner());g.value(id,"dbc:targetTable",k.targetTable());g.value(id,"rdfs:comment",meaning.relations().get(k.name()));
            for(int i=0;i<k.columns().size();i++){
                String pair=id+"/position/"+(i+1);g.iri(id,"dbc:keyPart",pair);g.integer(pair,"dbc:position",i+1);g.iri(pair,"dbc:sourceColumn",root+"/column/"+part(k.columns().get(i)));if(i<k.targetColumns().size())g.value(pair,"dbc:targetColumn",k.targetColumns().get(i));
            }
        }
        com.dbcompanion.model.OntologyRelations.validate(entry.document().links());
        for(var link:entry.document().links()){
            String id=version+"/relationship/"+link.id();g.iri(root,"dbc:relationshipReview",id);g.type(id,link.status().equals("CANDIDATE")?"dbc:RelationshipCandidate":"dbc:RelationshipReview");
            g.value(id,"dbc:state",link.status());g.value(id,"rdfs:label",link.label());g.value(id,"dbc:conditionNote",link.condition());
            g.value(id,"dbc:origin",link.origin());g.value(id,"dbc:actor",link.actor());g.value(id,"dbc:reviewedAt",link.reviewedAt());
            g.iri(id,"dbc:sourceVersion",document+"/revision/"+link.sourceRevision());
            g.iri(id,"dbc:targetVersion","urn:uuid:"+link.targetDocumentId()+"/revision/"+link.targetRevision());
            g.value(id,"dbc:targetOwner",link.targetSchema());g.value(id,"dbc:targetTable",link.targetTable());
            link.evidence().forEach(value->g.value(id,"dbc:evidence",value));
            for(int i=0;i<link.sourceColumns().size();i++){String pair=id+"/position/"+(i+1);g.iri(id,"dbc:columnMapping",pair);g.integer(pair,"dbc:position",i+1);
                g.value(pair,"dbc:sourceColumnName",link.sourceColumns().get(i));g.value(pair,"dbc:targetColumnName",link.targetColumns().get(i));}
        }
        var evidence=entry.document().analysis();
        if(evidence!=null){
            com.dbcompanion.model.OntologyAnalysis.validate(evidence);
            String analysis=version+"/analysis";g.iri(version,"dbc:analysis",analysis);g.type(analysis,"dbc:ReviewedSuggestion");
            g.value(analysis,"dbc:generatedAt",evidence.generatedAt());
            for(var ref:evidence.sources())g.iri(analysis,"dbc:basedOn","urn:uuid:"+ref.documentId()+"/revision/"+ref.revision());
            int i=0;for(var accepted:evidence.accepted()){
                String item=analysis+"/item/"+(++i);g.iri(analysis,"dbc:adopted",item);
                g.value(item,"dbc:field",accepted.field());g.value(item,"dbc:name",accepted.name());g.value(item,"rdfs:comment",accepted.value());
                g.value(item,"dbc:reason",accepted.reason());g.value(item,"dbc:uncertainty",accepted.uncertainty());
            }
        }
        return new Export(g.turtle.toString(),document,version,root,PREFIXES,g.triples);
    }
}
