package com.dbcompanion.service;

import com.dbcompanion.common.db.JdbcNetworkTimeout;
import com.dbcompanion.common.db.OracleTextSql;
import com.dbcompanion.common.db.PoolSession;
import com.dbcompanion.common.db.SessionDataSource;
import com.dbcompanion.model.Ontology;
import com.dbcompanion.model.OntologyScope;
import com.dbcompanion.model.OntologyValues;
import com.dbcompanion.model.Ontology.*;
import com.dbcompanion.model.ColumnInfo;
import com.dbcompanion.model.OntologyGovernance.*;
import com.dbcompanion.repository.OntologyRepository;
import java.time.Instant;
import java.util.*;
import java.util.function.Supplier;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;

/** Exact/registered-alias retrieval and explicit snapshot comparison. Oracle Text is never assumed. */
@Service
public class OntologyGovernanceService {
    private static final int LIMIT=20,CANDIDATES=100;
    private final SessionDataSource source;private final OntologyRepository repository;private final TransactionTemplate read,write;
    private final Map<PoolSession,ContextPreview> contexts=Collections.synchronizedMap(new WeakHashMap<>());
    private final Map<PoolSession,Drift> drifts=Collections.synchronizedMap(new WeakHashMap<>());
    private final Map<PoolSession,Snapshot> inspectedSnapshots=Collections.synchronizedMap(new WeakHashMap<>());
    private record PendingText(TextActivationPreview preview,String profileVersion,List<OntologyRepository.TextCacheRow> rows) {}
    private final Map<PoolSession,PendingText> textActivations=Collections.synchronizedMap(new WeakHashMap<>());
    private final Map<PoolSession,Boolean> textUncertain=Collections.synchronizedMap(new WeakHashMap<>());
    private final JsonMapper json=new JsonMapper();
    public OntologyGovernanceService(SessionDataSource source,OntologyRepository repository){this.source=source;this.repository=repository;var manager=new DataSourceTransactionManager(source);read=new TransactionTemplate(manager);read.setReadOnly(true);read.setTimeout(Ontology.READ_TIMEOUT_SECONDS);write=new TransactionTemplate(manager);write.setTimeout(15);}
    private void scope(PoolSession session,String schema){Ontology.name(schema);if(!schema.equals(session.metadata().selectedSchema()))throw new Ontology.Failure(409,"stale");}
    private <T>T query(PoolSession session,Supplier<T> action){source.bind(session.pool(),session.metadata().info().username());try{return read.execute(s->JdbcNetworkTimeout.execute(source,40_000,action));}finally{source.clear();}}
    private <T>T writeQuery(PoolSession session,Supplier<T> action){source.bind(session.pool(),session.metadata().info().username());try{return write.execute(s->action.get());}finally{source.clear();}}
    public GlossaryResult search(PoolSession session,String schema,String question){synchronized(session){scope(session,schema);return scopeRequired();}}
    public GlossaryResult search(PoolSession session,String schema,String question,List<String> tables){synchronized(session){scope(session,schema);var names=scopeNames(tables);if(names.isEmpty())return scopeRequired();validQuestion(question);return query(session,()->searchProjected(schema,session.metadata().info().username(),question,names));}}
    private GlossaryResult scopeRequired(){return new GlossaryResult("SCOPE_REQUIRED","NOT_QUERIED",List.of(),Instant.now().toString(),"Choose 1 to 100 approved tables; no ontology payload was read.",false);}
    private static List<String> scopeNames(List<String> tables){if(tables==null||tables.isEmpty())return List.of();var names=OntologyScope.names(tables);if(names.size()>100)throw new Ontology.Failure(413,"limit");return names;}
    private static void validQuestion(String question){if(question==null||question.isBlank()||question.codePointCount(0,question.length())>256||question.indexOf(0)>=0)throw new Ontology.Failure(400,"invalid");}
    private GlossaryResult searchProjected(String schema,String login,String question,List<String> names){var approved=repository.approvedGlossaryRevisions(schema,login,names);if(approved.size()!=names.size())throw new Ontology.Failure(409,"scope.missingDefinition");var collector=new HitCollector();for(var row:repository.glossary(schema,login,names)){if(!Objects.equals(approved.get(row.table()),row.revision()))throw new Ontology.Failure(409,"scope.missingDefinition");addProjection(collector,row,question);}return collector.result();}
    private void addProjection(HitCollector hits,OntologyRepository.GlossaryProjection row,String question){hits.add(row.table(),row.revision(),"TABLE",row.table(),row.concept(),row.description(),List.of(),question);try{for(var entry:map(row.columns()).entrySet()){if(!(entry.getKey() instanceof String column)||!(entry.getValue() instanceof Map<?,?> value))throw malformed();var definition=value.get("definition");if(definition==null)continue;if(!(definition instanceof Map<?,?> def))throw malformed();hits.add(row.table(),row.revision(),"COLUMN",column,string(def.get("label"),true),string(value.get("description"),false),strings(def.get("aliases")),question);}for(Object raw:list(row.mappings())){if(!(raw instanceof Map<?,?> mapping))throw malformed();hits.add(row.table(),row.revision(),"VALUE_MAPPING",string(mapping.get("id"),true),string(mapping.get("label"),true),string(mapping.get("description"),false),strings(mapping.get("aliases")),question);}}catch(Ontology.Failure ex){throw ex;}catch(RuntimeException ex){throw malformed();}}
    private Map<?,?> map(String raw){if(raw==null)return Map.of();Object value=json.readValue(raw,Object.class);if(!(value instanceof Map<?,?> map))throw malformed();return map;}
    private List<?> list(String raw){if(raw==null)return List.of();Object value=json.readValue(raw,Object.class);if(!(value instanceof List<?> list))throw malformed();return list;}
    private static String string(Object value,boolean required){if(value==null&&!required)return "";if(!(value instanceof String text)||text.length()>8000||text.indexOf(0)>=0||(required&&text.isBlank()))throw malformed();return text;}
    private static List<String> strings(Object value){if(value==null)return List.of();if(!(value instanceof List<?> rows)||rows.size()>10)throw malformed();var result=new ArrayList<String>();for(Object row:rows)result.add(string(row,true));return List.copyOf(result);}
    private static Ontology.Failure malformed(){return new Ontology.Failure(409,"glossary.malformed");}
    public ContextPreview context(PoolSession session,String schema,String question,List<String> tables,String profile){var names=scopeNames(tables);if(names.isEmpty())throw new Ontology.Failure(400,"scope.selection");profile(profile);var result=search(session,schema,question,names);var value=new ContextPreview(UUID.randomUUID().toString(),schema,question,names,profile,result.hits(),Instant.now().plusSeconds(300).toString());contexts.put(session,value);return value;}
    /** Text candidates are converted only after current approved identity/revision revalidation. */
    public ContextPreview textContext(PoolSession session,String schema,String question,List<String> tables,String profile){var result=textSearch(session,schema,question,tables,profile);if(!"AVAILABLE".equals(result.status()))throw new Ontology.Failure(409,"text.unconfirmed");var hits=result.hits().stream().map(v->new GlossaryHit(v.table(),v.revision(),v.term(),v.term(),v.definition(),v.aliases(),"ORACLE_TEXT",v.sourceKind(),v.sourceId())).toList();if(hits.isEmpty())throw new Ontology.Failure(409,"text.unconfirmed");var names=scopeNames(tables);var value=new ContextPreview(UUID.randomUUID().toString(),schema,question,names,profile,hits,Instant.now().plusSeconds(300).toString());contexts.put(session,value);return value;}
    private static void profile(String value){if(value==null||value.isBlank()||value.length()>256||value.indexOf(0)>=0)throw new Ontology.Failure(400,"invalid");}
    public Context consume(PoolSession session,String schema,String question,List<String> tables,String profile,String token,List<String> selected){synchronized(session){scope(session,schema);var names=scopeNames(tables);profile(profile);var preview=contexts.remove(session);if(preview==null||!preview.token().equals(token)||!preview.schema().equals(schema)||!preview.question().equals(question)||!preview.tables().equals(names)||!preview.profile().equals(profile)||Instant.now().isAfter(Instant.parse(preview.expiresAt())))throw new Ontology.Failure(409,"stale");if(selected==null||selected.isEmpty()||selected.size()>LIMIT)throw new Ontology.Failure(400,"invalid");return query(session,()->consumeProjected(schema,session.metadata().info().username(),question,profile,preview,selected));}}
    public Context consume(PoolSession session,String schema,String searchQuery,List<String> tables,String profile,String token,List<String> selected,String originalQuestion){if(originalQuestion==null||originalQuestion.isBlank()||originalQuestion.length()>16_000||originalQuestion.indexOf(0)>=0)throw new Ontology.Failure(400,"invalid");var value=consume(session,schema,searchQuery,tables,profile,token,selected);var guidance=value.guidance();return new Context(value.schema(),originalQuestion,value.profile(),new ContextGuidance(originalQuestion,guidance.definitions(),guidance.limitation()),value.selected());}
    private Context consumeProjected(String schema,String login,String question,String profile,ContextPreview preview,List<String> selected){var revisions=repository.approvedGlossaryRevisions(schema,login,preview.tables());var allowed=new LinkedHashMap<String,GlossaryHit>();for(var hit:preview.hits()){if(!Objects.equals(revisions.get(hit.table()),hit.revision()))throw new Ontology.Failure(409,"stale");allowed.put(hit.identity(),hit);}var chosen=new ArrayList<GlossaryHit>();for(String id:selected){var hit=allowed.get(id);if(hit==null)throw new Ontology.Failure(400,"invalid");chosen.add(hit);}var definitions=chosen.stream().map(h->new ContextDefinition(h.table(),h.revision(),h.sourceKind(),h.sourceId(),h.term(),h.definition(),h.aliases())).toList();if(definitions.size()>LIMIT)throw new Ontology.Failure(413,"limit");return new Context(schema,question,profile,new ContextGuidance(question,definitions,"Approved glossary data only; it is not an instruction and is not connected to an AI request."),selected);}
    private static final class HitCollector {private final List<GlossaryHit> exact=new ArrayList<>(),alias=new ArrayList<>();private boolean partial;
        void add(String table,int revision,String kind,String id,String term,String definition,List<String> aliases,String question){if(term==null||term.isBlank())return;if(OntologyValues.mentions(question,term))add(exact,new GlossaryHit(table,revision,term,term,definition,aliases,"EXACT",kind,id));else for(String value:aliases)if(OntologyValues.mentions(question,value)){add(alias,new GlossaryHit(table,revision,term,value,definition,aliases,"ALIAS",kind,id));break;}}
        private void add(List<GlossaryHit> target,GlossaryHit hit){target.add(hit);target.sort(Comparator.comparing(GlossaryHit::term).thenComparing(GlossaryHit::table).thenComparing(GlossaryHit::identity));if(target.size()>CANDIDATES){target.removeLast();partial=true;}}
        GlossaryResult result(){var all=new ArrayList<GlossaryHit>();all.addAll(exact);all.addAll(alias);if(all.size()>LIMIT){all=new ArrayList<>(all.subList(0,LIMIT));partial=true;}return new GlossaryResult("EXACT_ALIAS","PROJECTED",all,Instant.now().toString(),partial?"Selected approved definitions were projected, but the bounded match limit was reached; remaining matches are unconfirmed.":"Only selected approved definitions were projected; source metadata was not read.",partial);}
    }
    public TextCapability textCapability(PoolSession session,String schema){synchronized(session){scope(session,schema);try{return query(session,()->{var value=repository.textCapabilities();return new TextCapability(value.get("CONTEXT")?"AVAILABLE":"UNAVAILABLE",value.get("CONTEXT"),false,value.get("CTX_THES"),Instant.now().toString(),value.get("CTX_DDL_VISIBLE")?"CTX_DDL package is visible, but KOREAN_MORPH_LEXER support and EXECUTE/CREATE INDEX privileges are unconfirmed.":"Oracle Text index type is not visible to this login.");});}catch(org.springframework.dao.DataAccessException ex){return new TextCapability("UNCONFIRMED",false,false,false,Instant.now().toString(),"Dictionary access failed; this is not evidence that Oracle Text is unsupported.");}}}
    public TextInstallGuide textInstallGuide(PoolSession session,String schema){synchronized(session){scope(session,schema);var plan=OracleTextSql.installPlan(schema);return new TextInstallGuide("UNVERIFIED","Copy-only plan: no table, preference, thesaurus, index, or search query is executed. Package visibility does not prove EXECUTE access or Korean lexer support. "+String.join(" ",plan.warnings()),plan.requiredPrivileges(),plan.ddl());}}
    public TextActivationPreview textActivationPreview(PoolSession session,String schema,String profile,List<String> tables,String operation){synchronized(session){
        scope(session,schema);profile(profile);var names=scopeNames(tables);var login=session.metadata().info().username();
        if(!schema.equals(login))throw new Ontology.Failure(403,"ownerRequired");
        if(textUncertain.containsKey(session))throw new Ontology.Failure(409,"text.partial");
        if(names.isEmpty()||!("INSTALL".equals(operation)||"SYNC".equals(operation)))throw new Ontology.Failure(400,"invalid");
        return query(session,()->{
            String version=repository.textProfileVersion(schema,login,profile);
            var revisions=repository.approvedGlossaryRevisions(schema,login,names);
            if(revisions.size()!=names.size())throw new Ontology.Failure(409,"scope.missingDefinition");
            var rows=textCacheRows(repository.glossary(schema,login,names),profile);
            if(rows.stream().anyMatch(row->!Objects.equals(revisions.get(row.table()),row.revision())))throw new Ontology.Failure(409,"stale");
            var statements=repository.textActivationCheck(schema,login,profile,operation,rows);
            var impacts=new ArrayList<>(OracleTextSql.installPlan(schema,profile).requiredPrivileges());
            impacts.add("Explicit owner-bound "+operation+" only; no DELETE, DROP, GRANT, automatic retry, or all-index operation.");
            impacts.add("DDL and SYNC_INDEX may commit implicitly. Unknown or partial results block further activation in this session; inspect actual objects before reconnecting.");
            impacts.add("At most 100 tables, 2000 terms total and 500 terms per table. Terms and registered aliases only; no cross-table or cross-profile synonym dictionaries.");
            impacts.add("INSTALL creates the term cache, Korean lexer and named index. SYNC writes approved rows and immutable scoped thesauri; existing dictionaries and old revisions are never deleted.");
            var value=new TextActivationPreview(UUID.randomUUID().toString(),operation,schema,login,profile,names,revisions,rows.size(),statements,impacts,Instant.now().plusSeconds(180).toString());
            textActivations.put(session,new PendingText(value,version,rows));return value;
        });
    }}
    public TextActivationResult activateText(PoolSession session,String schema,String profile,List<String> tables,String operation,String token,boolean confirmed){synchronized(session){
        scope(session,schema);var names=scopeNames(tables);var pending=textActivations.remove(session);
        if(pending==null||textUncertain.containsKey(session))throw new Ontology.Failure(409,"stale");
        var preview=pending.preview();
        if(!confirmed||!preview.token().equals(token)||!preview.operation().equals(operation)||!preview.schema().equals(schema)||!preview.profile().equals(profile)||!preview.tables().equals(names)||Instant.now().isAfter(Instant.parse(preview.expiresAt())))throw new Ontology.Failure(409,"stale");
        boolean[] started={false};
        try{return writeQuery(session,()->{
            var login=session.metadata().info().username();
            if(!schema.equals(login)||!pending.profileVersion().equals(repository.textProfileVersion(schema,login,profile))
                    ||!repository.approvedGlossaryRevisions(schema,login,names).equals(preview.revisions())
                    ||!textCacheRows(repository.glossary(schema,login,names),profile).equals(pending.rows()))throw new Ontology.Failure(409,"stale");
            repository.textActivationCheck(schema,login,profile,operation,pending.rows());
            started[0]=true;
            if("INSTALL".equals(operation))repository.installText(schema,login,profile);else repository.syncText(schema,login,profile,pending.rows());
            return new TextActivationResult(operation,"COMPLETED",preview.candidateCount(),Instant.now().toString(),"The explicit operation returned normally. Search revalidates current approved revisions and identities; this does not prove business correctness.");
        });}catch(RuntimeException ex){
            if(!started[0])throw ex;
            textUncertain.put(session,true);
            return new TextActivationResult(operation,"CHECK_REQUIRED",preview.candidateCount(),Instant.now().toString(),"Partial or committed changes may exist. No rollback or retry is claimed. Inspect the exact preview targets before reconnecting; further activation is blocked in this session.");
        }
    }}
    private List<OntologyRepository.TextCacheRow> textCacheRows(List<OntologyRepository.GlossaryProjection> rows,String profile){var sources=approvedTextSources(rows);var result=new ArrayList<OntologyRepository.TextCacheRow>();for(var entry:sources.entrySet()){var parts=entry.getKey().split("\\u0000",-1);if(parts.length!=4)throw malformed();var source=entry.getValue();String aliases=json.writeValueAsString(source.aliases());String search=source.term()+"\n"+source.definition()+"\n"+String.join("\n",source.aliases());String id=UUID.nameUUIDFromBytes((profile+"\u0000"+entry.getKey()).getBytes(java.nio.charset.StandardCharsets.UTF_8)).toString();result.add(new OntologyRepository.TextCacheRow(id,parts[0],Integer.parseInt(parts[1]),parts[2],parts[3],source.term(),source.definition(),aliases,search));}if(result.isEmpty()||result.size()>2000)throw new Ontology.Failure(413,"limit");result.sort(Comparator.comparing(OntologyRepository.TextCacheRow::id));return List.copyOf(result);}
    /** Executes only a bounded SELECT after both approval scope and search-object visibility checks. */
    public TextSearchResult textSearch(PoolSession session,String schema,String question,List<String> tables,String profile){synchronized(session){scope(session,schema);var names=scopeNames(tables);if(names.isEmpty())return new TextSearchResult("ORACLE_TEXT","SCOPE_REQUIRED","NOT_QUERIED",List.of(),Instant.now().toString(),"Choose 1 to 100 approved tables; no Oracle Text query was executed.");validQuestion(question);profile(profile);try{return query(session,()->textSearchProjected(schema,session.metadata().info().username(),question,names,profile));}catch(org.springframework.dao.DataAccessException ex){return new TextSearchResult("ORACLE_TEXT","UNCONFIRMED","UNCONFIRMED",List.of(),Instant.now().toString(),"Dictionary or Oracle Text query access failed; this does not establish that the table, index, lexer, or privilege is absent.");}}}
    private TextSearchResult textSearchProjected(String schema,String login,String question,List<String> names,String profile){
        var approved=repository.approvedGlossaryRevisions(schema,login,names);if(approved.size()!=names.size())throw new Ontology.Failure(409,"scope.missingDefinition");
        var availability=repository.textSearchAvailability(schema,login);if(!"READY".equals(availability.status()))return new TextSearchResult("ORACLE_TEXT",availability.status(),"UNCONFIRMED",List.of(),Instant.now().toString(),availability.limitation());
        var projected=repository.glossary(schema,login,names);
        var before=approvedTextSources(projected);
        if(before.isEmpty())return textUnconfirmed("No approved terms are available in the selected scope; the cache was not queried.");
        List<OntologyRepository.TextProjection> rows;
        try{rows=repository.textSearch(schema,login,profile,approved,question,LIMIT,textCacheRows(projected,profile));}
        catch(Ontology.Failure ex){if(ex.status()==409)return textUnconfirmed("The scoped Oracle Text storage is incomplete or does not match its approved source; inspect it before synchronizing.");throw ex;}
        var latest=repository.approvedGlossaryRevisions(schema,login,names);if(!approved.equals(latest))return textUnconfirmed("Approved revisions changed while the read-only Oracle Text query ran; its results were discarded.");
        var after=approvedTextSources(repository.glossary(schema,login,names));if(!before.equals(after))return textUnconfirmed("Approved source identities or definition payload changed while the read-only Oracle Text query ran; its results were discarded.");
        var hits=new ArrayList<TextSearchHit>();for(var row:rows){var source=after.get(textIdentity(row.table(),row.revision(),row.sourceKind(),row.sourceId()));if(!Objects.equals(approved.get(row.table()),row.revision())||source==null)return textUnconfirmed("An Oracle Text row did not match the current approved source identity; its results were discarded.");hits.add(new TextSearchHit(row.table(),row.revision(),row.sourceKind(),row.sourceId(),source.term(),source.definition(),source.aliases(),row.score()));}
        return new TextSearchResult("ORACLE_TEXT","AVAILABLE","UNCONFIRMED",hits,Instant.now().toString(),"Read-only Oracle Text results are ranked separately from exact/alias matches. Korean lexer behavior remains unconfirmed; no AI request was made.");
    }
    private static TextSearchResult textUnconfirmed(String limitation){return new TextSearchResult("ORACLE_TEXT","UNCONFIRMED","UNCONFIRMED",List.of(),Instant.now().toString(),limitation);}
    private record ApprovedTextSource(String term,String definition,List<String> aliases) { private ApprovedTextSource { aliases=List.copyOf(aliases); } }
    /** The cache supplies only candidate identity and ranking; display payload always comes from this projection. */
    private Map<String,ApprovedTextSource> approvedTextSources(List<OntologyRepository.GlossaryProjection> rows){var result=new LinkedHashMap<String,ApprovedTextSource>();for(var row:rows){try{var tableTerm=string(row.concept(),false);if(!tableTerm.isBlank())result.put(textIdentity(row.table(),row.revision(),"TABLE",row.table()),new ApprovedTextSource(tableTerm,string(row.description(),false),List.of()));for(var entry:map(row.columns()).entrySet()){if(!(entry.getKey() instanceof String column)||!(entry.getValue() instanceof Map<?,?> value))throw malformed();var definition=value.get("definition");if(definition==null)continue;if(!(definition instanceof Map<?,?> def))throw malformed();result.put(textIdentity(row.table(),row.revision(),"COLUMN",column),new ApprovedTextSource(string(def.get("label"),true),string(value.get("description"),false),strings(def.get("aliases"))));}for(Object raw:list(row.mappings())){if(!(raw instanceof Map<?,?> mapping))throw malformed();result.put(textIdentity(row.table(),row.revision(),"VALUE_MAPPING",string(mapping.get("id"),true)),new ApprovedTextSource(string(mapping.get("label"),true),string(mapping.get("description"),false),strings(mapping.get("aliases"))));}}catch(Ontology.Failure ex){throw ex;}catch(RuntimeException ex){throw malformed();}}return Map.copyOf(result);}
    private static String textIdentity(String table,int revision,String kind,String id){return table+"\u0000"+revision+"\u0000"+kind+"\u0000"+id;}
    public Drift drift(PoolSession session,String schema,String table){synchronized(session){scope(session,schema);Ontology.name(table);inspectedSnapshots.remove(session);var value=query(session,()->{try{repository.require(schema,session.metadata().info().username());}catch(Ontology.Failure ex){return new Drift(table,0,"",Instant.now().toString(),"SCOPE_UNAVAILABLE",List.of(),"Ontology storage is unavailable or not visible; no deletion conclusion was made.");}var baseline=repository.entry(schema,table,0);if(baseline==null)return new Drift(table,0,"",Instant.now().toString(),"BASELINE_MISSING",List.of(),"No saved ontology snapshot exists.");try{var current=repository.snapshot(session.metadata().info().database(),schema,table);inspectedSnapshots.put(session,current);return compare(baseline,current);}catch(Ontology.Failure ex){return new Drift(table,baseline.revision(),baseline.document().source().capturedAt(),Instant.now().toString(),ex.status()==404?"TABLE_NOT_VISIBLE":"READ_UNCONFIRMED",List.of(),"Current metadata is unavailable; absence is not treated as deletion.");}catch(org.springframework.dao.DataAccessException ex){return new Drift(table,baseline.revision(),baseline.document().source().capturedAt(),Instant.now().toString(),"READ_UNCONFIRMED",List.of(),"Current metadata could not be read; absence is not treated as deletion.");}});drifts.put(session,value);return value;}}
    public static Drift compare(Entry baseline,Snapshot current){var before=baseline.document().source();var changes=new ArrayList<Difference>();compareValue(changes,"TABLE_COMMENT",before.table(),before.comment(),current.comment());var oldColumns=new LinkedHashMap<String,ColumnInfo>();before.columns().forEach(c->oldColumns.put(c.name(),c));var newColumns=new LinkedHashMap<String,ColumnInfo>();current.columns().forEach(c->newColumns.put(c.name(),c));oldColumns.forEach((name,column)->{var now=newColumns.get(name);if(now==null)changes.add(new Difference("COLUMN",name,describe(column),"","REVIEW_REQUIRED"));else{compareValue(changes,"DATATYPE",name,column.dataType(),now.dataType());compareValue(changes,"NULLABLE",name,column.nullable(),now.nullable());compareValue(changes,"COLUMN_COMMENT",name,column.comment(),now.comment());}});newColumns.forEach((name,column)->{if(!oldColumns.containsKey(name))changes.add(new Difference("COLUMN",name,"",describe(column),"REVIEW_REQUIRED"));});compareKeys(changes,before.keys(),current.keys());if(!"SUCCESS".equals(current.annotationStatus()))return new Drift(before.table(),baseline.revision(),before.capturedAt(),Instant.now().toString(),"ANNOTATIONS_UNCONFIRMED",changes,"Current annotations were not successfully read; acceptance is blocked.");if(!"SUCCESS".equals(before.annotationStatus()))return new Drift(before.table(),baseline.revision(),before.capturedAt(),Instant.now().toString(),"ANNOTATION_BASELINE_REQUIRED",changes,"This historical baseline has no confirmed Annotation snapshot. Read current annotations and explicitly accept a new baseline; it is not unchanged.");compareAnnotations(changes,before.annotations(),current.annotations());return new Drift(before.table(),baseline.revision(),before.capturedAt(),Instant.now().toString(),changes.isEmpty()?"UNCHANGED":"REVIEW_REQUIRED",changes,"");}
    private static void compareKeys(List<Difference> changes,List<Key> before,List<Key> current){var old=new TreeMap<String,Key>();before.forEach(k->old.put(k.name(),k));var now=new TreeMap<String,Key>();current.forEach(k->now.put(k.name(),k));var names=new TreeSet<String>();names.addAll(old.keySet());names.addAll(now.keySet());for(String name:names)if(!Objects.equals(old.get(name),now.get(name)))changes.add(new Difference("KEY",name,Objects.toString(old.get(name),""),Objects.toString(now.get(name),""),"REVIEW_REQUIRED"));}
    private static void compareAnnotations(List<Difference> changes,List<Ontology.Annotation> before,List<Ontology.Annotation> current){var oldValues=new LinkedHashMap<String,Ontology.Annotation>();before.forEach(a->oldValues.put(annotationKey(a),a));var newValues=new LinkedHashMap<String,Ontology.Annotation>();current.forEach(a->newValues.put(annotationKey(a),a));var names=new TreeSet<String>();names.addAll(oldValues.keySet());names.addAll(newValues.keySet());for(String name:names){var old=oldValues.get(name);var now=newValues.get(name);if(!Objects.equals(old,now))changes.add(new Difference("ANNOTATION",name,annotationValue(old),annotationValue(now),"REVIEW_REQUIRED"));}}
    private static String annotationKey(Ontology.Annotation value){return Objects.toString(value.column(),"")+"\u0000"+value.name();}
    private static String annotationValue(Ontology.Annotation value){return value==null?"":Objects.toString(value.value(),"<empty>")+" · inherited="+(value.domainName()!=null);}
    private static void compareValue(List<Difference> changes,String kind,String name,String before,String current){if(!Objects.equals(before,current))changes.add(new Difference(kind,name,Objects.toString(before,""),Objects.toString(current,""),"REVIEW_REQUIRED"));}
    private static String describe(ColumnInfo column){return column.dataType()+" · "+Objects.toString(column.comment(),"");}
    public Entry accept(PoolSession session,String schema,String table,int revision,String token,boolean confirmed){synchronized(session){scope(session,schema);var inspected=drifts.remove(session);var preview=inspectedSnapshots.remove(session);if(inspected==null||preview==null||!inspected.checkedAt().equals(token)||!inspected.table().equals(table)||inspected.baselineRevision()!=revision||(!"REVIEW_REQUIRED".equals(inspected.status())&&!"UNCHANGED".equals(inspected.status())&&!"ANNOTATION_BASELINE_REQUIRED".equals(inspected.status())))throw new Ontology.Failure(409,"stale");if(!"SUCCESS".equals(preview.annotationStatus()))throw new Ontology.Failure(409,"stale");if(!confirmed)throw new Ontology.Failure(400,"confirmRequired");return writeQuery(session,()->{repository.require(schema,session.metadata().info().username());var before=repository.entry(schema,table,0);if(before==null||before.revision()!=revision)throw new Ontology.Failure(409,"stale");Snapshot current;try{current=repository.snapshot(session.metadata().info().database(),schema,table);}catch(RuntimeException ex){throw new Ontology.Failure(409,"stale");}if(!"SUCCESS".equals(current.annotationStatus())||!sameSnapshot(preview,current))throw new Ontology.Failure(409,"stale");return repository.append(schema,table,revision,before.state(),new Document(1,current,rebase(before.document().meaning(),current),"SNAPSHOT_ACCEPTED",null,before.document().analysis(),before.document().links()));});}}
    private static boolean sameSnapshot(Snapshot a,Snapshot b){return a.database().equals(b.database())&&a.schema().equals(b.schema())&&a.table().equals(b.table())&&Objects.equals(a.comment(),b.comment())&&a.columns().equals(b.columns())&&a.keys().equals(b.keys())&&a.annotations().equals(b.annotations())&&a.annotationStatus().equals(b.annotationStatus());}
    public static Meaning rebase(Meaning old,Snapshot current){var initial=Ontology.initial(current);var columns=new LinkedHashMap<String,ColumnMeaning>();initial.columns().forEach((name,value)->columns.put(name,old.columns().getOrDefault(name,value)));var relations=new LinkedHashMap<String,String>();initial.relations().forEach((name,value)->relations.put(name,old.relations().getOrDefault(name,value)));var values=old.valueMappings().stream().filter(value->columns.containsKey(value.column())).toList();return Ontology.validate(current,new Meaning(old.concept(),old.description(),columns,relations,values));}
}
