package com.dbcompanion.service;

import com.dbcompanion.common.db.*;
import com.dbcompanion.model.*;
import com.dbcompanion.repository.AppRecordRepository;
import java.time.Instant;
import java.util.*;
import java.util.function.Supplier;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;

/** Owner-schema persistence for user-selected issue reports and immutable attempts. */
@Service
public class ProblemQuestionService {
    private final SessionDataSource source; private final AppRecordRepository records; private final JsonMapper json; private final TransactionTemplate read,write;
    public ProblemQuestionService(SessionDataSource source,AppRecordRepository records,JsonMapper json){this.source=source;this.records=records;this.json=json;var manager=new DataSourceTransactionManager(source);read=new TransactionTemplate(manager);read.setReadOnly(true);read.setTimeout(15);write=new TransactionTemplate(manager);write.setTimeout(15);}
    private String schema(PoolSession s){String schema=s.metadata().selectedSchema(),login=s.metadata().info().username();QueryArchive.owner(schema,login);return schema;}
    private <T>T tx(PoolSession s,TransactionTemplate t,Supplier<T> work){return tx(s,t,true,work);}
    private <T>T tx(PoolSession s,TransactionTemplate t,boolean requireStorage,Supplier<T> work){source.bind(s.pool(),s.metadata().info().username());try{return t.execute(x->{if(requireStorage)requireStorage(s);return work.get();});}finally{source.clear();}}
    private void requireStorage(PoolSession s){
        switch(records.status(schema(s),s.metadata().info().username())){
            case "READY" -> { }
            case "MISSING" -> throw new AiAssistant.Failure(409,"problemQuestion.storageMissing","문제 질문 저장소(DBC_APP_RECORD)가 아직 없습니다. 저장소를 준비한 후 다시 확인해 주세요.");
            case "MISMATCH" -> throw new AiAssistant.Failure(409,"problemQuestion.storageMismatch","DBC_APP_RECORD의 구조가 앱 요구사항과 다릅니다. 기존 테이블을 변경하지 않았습니다. 관리자에게 확인해 주세요.");
            default -> throw new AiAssistant.Failure(503,"problemQuestion.storageUnavailable","문제 질문 저장소의 상태를 확인하지 못했습니다. 연결과 조회 권한을 확인한 뒤 다시 시도해 주세요.");
        }
    }
    public String status(PoolSession s){return tx(s,read,false,()->records.status(schema(s),s.metadata().info().username()));}
    public String save(PoolSession s,ProblemQuestion.Create request){var value=ProblemQuestion.create(request);return tx(s,write,()->{String schema=schema(s),id=UUID.randomUUID().toString();var parent=new ProblemQuestion.Parent(1,id,value.question(),value.description(),value.expected(),value.expectedSql(),value.status(),false,Instant.now(),Instant.now());saveRecord(schema,id,ProblemQuestion.TYPE,parent);return id;});}
    /** Captures a user-confirmed current test result; this is persistence only, never another provider call. */
    public String saveLatest(PoolSession s,ProblemQuestion.Create request,boolean includeSnapshots){return saveCaptured(s,request,capture(s,includeSnapshots));}
    public String saveLatestAttempt(PoolSession s,String parentId,boolean includeSnapshots){var capture=capture(s,includeSnapshots);var parent=detail(s,parentId).parent();return saveCapturedAttempt(s,parentId,parent.updatedAt(),capture);}
    /** Immutable observation shared by single-result and A/B explicit-save paths. */
    public record Capture(SelectAiTest.Outcome outcome,ProblemQuestion.Snapshot options,ProblemQuestion.Snapshot prompt,ProblemQuestion.Snapshot metadata,ProblemQuestion.Snapshot feedback) {}
    private Capture capture(PoolSession s,boolean include){var state=s.metadata().aiTest();final SelectAiTest.Outcome outcome;final SelectAiTest.Outcome prompt;final SelectAiInspection.Snapshot inspection;synchronized(state){state.idle();outcome=state.latest();prompt=state.prompt();inspection=state.inspection();}return capture(outcome,prompt,inspection,include);}
    public Capture capture(SelectAiTest.Outcome outcome,SelectAiTest.Outcome prompt,SelectAiInspection.Snapshot inspection,boolean include){if(outcome==null)throw new AiAssistant.Failure(409,"problemQuestion.noResult","저장할 Select AI 결과가 없습니다.");if(!include)return new Capture(outcome,unavailable("NOT_REQUESTED"),unavailable("NOT_REQUESTED"),unavailable("NOT_REQUESTED"),unavailable("NOT_REQUESTED"));boolean same=inspection!=null&&inspection.profile().equals(outcome.profile())&&inspection.question().equals(outcome.question());java.util.function.Function<Instant,String> kind=t->t.isAfter(outcome.requestedAt())?"POST_GENERATION_READ":t.isBefore(outcome.requestedAt())?"PRE_GENERATION_READ":"CAPTURED";var options=same?captured(json.writeValueAsString(inspection.settings()),kind.apply(inspection.checkedAt()),inspection.checkedAt()):unavailable("NOT_QUERIED");var metadata=same&&!inspection.tables().isEmpty()?captured(json.writeValueAsString(Map.of("tables",inspection.tables())),inspection.tables().stream().anyMatch(t->t.error()!=null)?"PARTIAL_OR_ERROR":kind.apply(inspection.tables().stream().map(SelectAiInspection.Table::checkedAt).max(Instant::compareTo).orElse(inspection.checkedAt())),inspection.tables().stream().map(SelectAiInspection.Table::checkedAt).max(Instant::compareTo).orElse(inspection.checkedAt())):unavailable("NOT_QUERIED");var ft=same&&inspection.feedback()!=null?java.util.stream.Stream.concat(java.util.stream.Stream.of(inspection.feedback().checkedAt()),inspection.feedbackDetails().stream().map(SelectAiInspection.FeedbackDetail::checkedAt)).max(Instant::compareTo).orElse(inspection.feedback().checkedAt()):null;var feedback=ft!=null?captured(json.writeValueAsString(Map.of("page",inspection.feedback(),"details",inspection.feedbackDetails())),inspection.feedback().error()!=null?"ERROR":kind.apply(ft),ft):unavailable("NOT_QUERIED");boolean samePrompt=prompt!=null&&prompt.action()==SelectAiTest.Action.PROMPT&&prompt.profile().equals(outcome.profile())&&prompt.question().equals(outcome.question())&&Objects.equals(prompt.evidence(),outcome.evidence())&&BusinessGlossary.same(prompt.glossary(),outcome.glossary());var promptSnapshot=samePrompt&&prompt.error()==null&&prompt.text()!=null?captured(prompt.text(),"RECONSTRUCTED_SHOWPROMPT",prompt.requestedAt()):samePrompt?new ProblemQuestion.Snapshot("","ERROR_SHOWPROMPT",prompt.requestedAt()):unavailable("NOT_QUERIED");return new Capture(outcome,options,promptSnapshot,metadata,feedback);}
    private ProblemQuestion.Snapshot unavailable(String availability){return new ProblemQuestion.Snapshot("",availability,null);}
    /** Stored diagnostics are defensive copies: provider/metadata values cannot retain credentials or key material. */
    private ProblemQuestion.Snapshot captured(String value,String availability,Instant checkedAt){return new ProblemQuestion.Snapshot(ProblemQuestion.optional(value,ProblemQuestion.MAX_PAYLOAD,"problemQuestion.snapshot"),availability,checkedAt);}
    public String saveCaptured(PoolSession s,ProblemQuestion.Create request,Capture capture){var value=ProblemQuestion.create(request);return tx(s,write,()->{String schema=schema(s),id=UUID.randomUUID().toString();var parent=new ProblemQuestion.Parent(1,id,value.question(),value.description(),value.expected(),value.expectedSql(),value.status(),false,Instant.now(),Instant.now());saveRecord(schema,id,ProblemQuestion.TYPE,parent);saveCapturedAttempt(schema,id,capture);return id;});}
    public String saveCapturedAttempt(PoolSession s,String parentId,Instant expectedParentVersion,Capture capture){if(expectedParentVersion==null)throw AiAssistant.stale();return tx(s,write,()->{String schema=schema(s);var parent=records.lockProblem(schema,ProblemQuestion.id(parentId));if(!expectedParentVersion.equals(parent.updatedAt()))throw AiAssistant.stale();return saveCapturedAttempt(schema,parent.id(),capture);});}
    private String saveCapturedAttempt(String schema,String parentId,Capture capture){var outcome=capture.outcome();var profile=outcome.profile();var options=capture.options();var prompt=capture.prompt();var metadata=capture.metadata();var feedback=capture.feedback();String diagnostic=ProblemQuestion.optional(outcome.error(),8_000,"problemQuestion.error");if(outcome.code()!=null&&!outcome.code().isBlank())diagnostic+=(diagnostic.isBlank()?"":"\n")+"code="+ProblemQuestion.optional(outcome.code(),128,"problemQuestion.code");if(outcome.phase()!=null&&!outcome.phase().isBlank())diagnostic+=(diagnostic.isBlank()?"":"\n")+"phase="+ProblemQuestion.optional(outcome.phase(),128,"problemQuestion.phase");boolean failed=outcome.error()!=null&&!outcome.error().isBlank();String conditions=capturedConditions(outcome);var attempt=new ProblemQuestion.Attempt(1,UUID.randomUUID().toString(),parentId,ProblemQuestion.optional(outcome.question(),ProblemQuestion.MAX_TEXT,"problemQuestion.question"),conditions,ProblemQuestion.optional(outcome.text(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.response"),outcome.action()==SelectAiTest.Action.SQL&&!failed?ProblemQuestion.optional(outcome.text(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.sql"):"",diagnostic,ProblemQuestion.optional(profile.selection().owner()+"."+profile.selection().name(),512,"problemQuestion.profile"),ProblemQuestion.optional(profile.model(),512,"problemQuestion.model"),"","","","","USER_SELECTED","INDIVIDUAL_SNAPSHOTS",outcome.requestedAt(),outcome.elapsedMillis(),options,prompt,metadata,feedback);if(json.writeValueAsString(attempt).length()>ProblemQuestion.MAX_PAYLOAD)throw new AiAssistant.Failure(413,"problemQuestion.limit","선택한 저장 자료가 보관 한도를 초과합니다.");saveRecord(schema,attempt.id(),ProblemQuestion.ATTEMPT_TYPE,attempt);return parentId;}
    private String capturedConditions(SelectAiTest.Outcome outcome){
        var data=new LinkedHashMap<String,Object>();
        if(outcome.confirmation()!=null){data.put("confirmationQuestion",outcome.confirmation().question());data.put("confirmationAnswer",outcome.confirmation().answer());data.put("conditions",outcome.confirmation().conditions());}
        if(outcome.glossary()!=null)data.put("businessGlossary",outcome.glossary());
        return data.isEmpty()?"":ProblemQuestion.optional(json.writeValueAsString(data),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.conditions");
    }
    public String saveAttempt(PoolSession s,ProblemQuestion.Attempt value){return saveAttemptInternal(s,value,null);}
    public String saveAttempt(PoolSession s,ProblemQuestion.Attempt value,Instant expectedParentVersion){if(expectedParentVersion==null)throw AiAssistant.stale();return saveAttemptInternal(s,value,expectedParentVersion);}
    private String saveAttemptInternal(PoolSession s,ProblemQuestion.Attempt value,Instant expectedParentVersion){if(value==null)throw new AiAssistant.Failure(400,"problemQuestion.invalid","문제 질문 정보를 확인해 주세요.");return tx(s,write,()->{String schema=schema(s);var parent=records.lockProblem(schema,ProblemQuestion.id(value.parentId()));if(expectedParentVersion!=null&&!parent.updatedAt().equals(expectedParentVersion))throw AiAssistant.stale();Instant captured=expectedParentVersion!=null&&value.capturedAt()!=null?value.capturedAt():Instant.now();String kind=expectedParentVersion==null?"MANUAL_ENTRY":ProblemQuestion.optional(value.snapshotKind(),64,"problemQuestion.snapshot"),availability=expectedParentVersion==null?"USER_SUPPLIED":ProblemQuestion.optional(value.availability(),64,"problemQuestion.availability");String id=UUID.randomUUID().toString();var attempt=new ProblemQuestion.Attempt(1,id,parent.id(),ProblemQuestion.text(value.input(),ProblemQuestion.MAX_TEXT,"problemQuestion.question"),ProblemQuestion.optional(value.conditions(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.conditions"),ProblemQuestion.optional(value.response(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.response"),ProblemQuestion.optional(value.sql(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.sql"),ProblemQuestion.optional(value.error(),8_000,"problemQuestion.error"),ProblemQuestion.optional(value.profile(),512,"problemQuestion.profile"),ProblemQuestion.optional(value.model(),512,"problemQuestion.model"),ProblemQuestion.optional(value.options(),16_000,"problemQuestion.options"),ProblemQuestion.optional(value.prompt(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.prompt"),ProblemQuestion.optional(value.metadata(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.metadata"),ProblemQuestion.optional(value.feedback(),ProblemQuestion.MAX_DESCRIPTION,"problemQuestion.feedback"),kind,availability,captured,Math.max(0,value.elapsedMillis()),null,null,null,null);if(json.writeValueAsString(attempt).length()>ProblemQuestion.MAX_PAYLOAD)throw new AiAssistant.Failure(413,"problemQuestion.limit","선택한 저장 자료가 보관 한도를 초과합니다.");saveRecord(schema,id,ProblemQuestion.ATTEMPT_TYPE,attempt);return id;});}
    private void saveRecord(String schema,String id,String type,Object payload){var tree=json.valueToTree(payload);records.begin(schema,id,type,tree);if(!records.finish(schema,id,"SUCCEEDED",tree))throw new AiAssistant.Failure(409,"problemQuestion.stale","저장 상태가 변경되었습니다.");}
    public ProblemQuestion.Page page(PoolSession s,String before){return tx(s,read,()->records.problemPage(schema(s),before));}
    public ProblemQuestion.Detail detail(PoolSession s,String id){return tx(s,read,()->records.problemDetail(schema(s),ProblemQuestion.id(id)));}
    public ProblemQuestion.Parent update(PoolSession s,String id,ProblemQuestion.Update request,Instant expectedUpdatedAt){if(request==null||request.status()==null||expectedUpdatedAt==null)throw new AiAssistant.Failure(400,"problemQuestion.invalid","문제 질문 정보를 확인해 주세요.");return tx(s,write,()->{String schema=schema(s);var current=records.lockProblem(schema,ProblemQuestion.id(id));if(!current.updatedAt().equals(expectedUpdatedAt))throw new AiAssistant.Failure(409,"problemQuestion.stale","문제 질문이 변경되었습니다. 다시 불러와 주세요.");var next=new ProblemQuestion.Parent(current.version(),current.id(),current.question(),current.description(),current.expected(),current.expectedSql(),request.status(),request.retained(),current.createdAt(),Instant.now());records.updateProblem(schema,next,expectedUpdatedAt);return next;});}
    /** Compares two immutable saved observations only; it never reconstructs or calls AI. */
    public Map<String,Object> compare(PoolSession s,String parentId,String leftId,String rightId){return tx(s,read,()->{var detail=records.problemDetail(schema(s),ProblemQuestion.id(parentId));var left=detail.attempts().stream().filter(a->a.id().equals(ProblemQuestion.id(leftId))).findFirst().orElseThrow(()->new AiAssistant.Failure(404,"problemQuestion.missing","실행 기록을 찾을 수 없습니다."));var right=detail.attempts().stream().filter(a->a.id().equals(ProblemQuestion.id(rightId))).findFirst().orElseThrow(()->new AiAssistant.Failure(404,"problemQuestion.missing","실행 기록을 찾을 수 없습니다."));var differences=new LinkedHashMap<String,Map<String,String>>();compare(differences,"conditions",left.conditions(),right.conditions());compare(differences,"response",left.response(),right.response());compare(differences,"sql",left.sql(),right.sql());compare(differences,"error",left.error(),right.error());compare(differences,"profile",left.profile(),right.profile());compare(differences,"model",left.model(),right.model());compareSnapshot(differences,"options",left.optionSnapshot(),left.options(),right.optionSnapshot(),right.options());compareSnapshot(differences,"prompt",left.promptSnapshot(),left.prompt(),right.promptSnapshot(),right.prompt());compareSnapshot(differences,"metadata",left.metadataSnapshot(),left.metadata(),right.metadataSnapshot(),right.metadata());compareSnapshot(differences,"feedback",left.feedbackSnapshot(),left.feedback(),right.feedbackSnapshot(),right.feedback());return Map.of("left",left.id(),"right",right.id(),"differences",differences,"comparisonKind","SAVED_SNAPSHOTS_ONLY");});}
    public static Map<String,String> canonical(ProblemQuestion.Snapshot snapshot,String legacy){return snapshot==null?Map.of("value",Objects.toString(legacy,""),"availability","LEGACY","checkedAt",""):Map.of("value",Objects.toString(snapshot.value(),""),"availability",Objects.toString(snapshot.availability(),""),"checkedAt",Objects.toString(snapshot.checkedAt(),""));}
    private void compareSnapshot(Map<String,Map<String,String>> values,String field,ProblemQuestion.Snapshot left,String leftLegacy,ProblemQuestion.Snapshot right,String rightLegacy){var a=canonical(left,leftLegacy);var b=canonical(right,rightLegacy);if(!a.equals(b))values.put(field,Map.of("left",a.toString(),"right",b.toString()));}
    private void compare(Map<String,Map<String,String>> values,String field,String left,String right){if(!Objects.equals(left,right))values.put(field,Map.of("left",left==null?"":left,"right",right==null?"":right));}
    public ProblemQuestion.DeletePreview deletePreview(PoolSession s,List<String> ids){return tx(s,read,()->records.problemDeletePreview(schema(s),ids));}
    public int delete(PoolSession s,List<String> ids,int expectedRecords,int expectedAttempts,String fingerprint,boolean confirmed){if(!confirmed)throw new AiAssistant.Failure(400,"problemQuestion.confirmDelete","삭제할 자료와 수를 확인해 주세요.");return tx(s,write,()->{var preview=records.problemDeletePreview(schema(s),ids);if(preview.records()!=expectedRecords||preview.attempts()!=expectedAttempts||!Objects.equals(preview.fingerprint(),fingerprint))throw new AiAssistant.Failure(409,"problemQuestion.stale","삭제 대상이 변경되었습니다.");return records.deleteProblems(schema(s),ids,fingerprint);});}
}
