CREATE TABLE DBC_AUDIT_ARCHIVE (
 RECORD_KEY VARCHAR2(64) PRIMARY KEY,
 SOURCE_DATABASE VARCHAR2(128) NOT NULL,
 DBID NUMBER, INSTANCE_ID NUMBER, SESSIONID NUMBER, ENTRY_ID NUMBER, STATEMENT_ID NUMBER,
 EXECUTION_ID VARCHAR2(64), SCN NUMBER, AUDIT_TYPE VARCHAR2(64),
 EVENT_TIMESTAMP_UTC TIMESTAMP(6) NOT NULL,
 DBUSERNAME VARCHAR2(128), END_USER_NAME VARCHAR2(256), SECURITY_CONTEXT_ID VARCHAR2(128),
 ACTION_NAME VARCHAR2(64), OBJECT_SCHEMA VARCHAR2(128), OBJECT_NAME VARCHAR2(128), RETURN_CODE NUMBER,
 UNIFIED_AUDIT_POLICIES VARCHAR2(4000), SQL_TEXT CLOB, RLS_INFO CLOB,
 CAPTURED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
