CREATE PACKAGE BODY DBC_AUDIT_ARCHIVER AS
 PROCEDURE COLLECT IS
  v_last TIMESTAMP; v_from TIMESTAMP; v_to TIMESTAMP:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  v_days NUMBER; v_added NUMBER:=0; v_seen NUMBER:=0; v_deleted NUMBER:=0;
  v_key VARCHAR2(64);
 BEGIN
  -- Locks also serialize a manual run against the scheduler. Commit data + checkpoint together.
  SELECT LAST_SCAN_TO,RETENTION_DAYS INTO v_last,v_days
  FROM DBC_AUDIT_ARCHIVE_CONFIG WHERE CONFIG_ID=1 AND VERSION_TAG='DBC_AUDIT_ARCHIVE_V1' FOR UPDATE NOWAIT;
  -- First run backfills available last 14 days. Subsequent runs overlap 24h for late visibility.
  v_from:=COALESCE(v_last-INTERVAL '1' DAY,v_to-INTERVAL '14' DAY);
  FOR r IN (
   SELECT a.*, @@KEY@@ AS RECORD_KEY
   FROM (
    SELECT DBID,INSTANCE_ID,SESSIONID,ENTRY_ID,STATEMENT_ID,EXECUTION_ID,SCN,AUDIT_TYPE,
     EVENT_TIMESTAMP_UTC,DBUSERNAME,END_USER_NAME,RAWTOHEX(END_USER_SECURITY_CONTEXT_ID) SECURITY_CONTEXT_ID,
     ACTION_NAME,OBJECT_SCHEMA,OBJECT_NAME,RETURN_CODE,UNIFIED_AUDIT_POLICIES,SQL_TEXT,RLS_INFO
    FROM @@AUDIT_VIEW@@
    WHERE END_USER_NAME IS NOT NULL AND EVENT_TIMESTAMP_UTC>=v_from AND EVENT_TIMESTAMP_UTC<v_to
      AND (v_days=0 OR EVENT_TIMESTAMP_UTC>=v_to-NUMTODSINTERVAL(v_days,'DAY'))
   ) a
  ) LOOP
   v_seen:=v_seen+1;
   v_key:=r.RECORD_KEY;
   BEGIN
    INSERT INTO DBC_AUDIT_ARCHIVE
     (RECORD_KEY,SOURCE_DATABASE,DBID,INSTANCE_ID,SESSIONID,ENTRY_ID,STATEMENT_ID,EXECUTION_ID,SCN,AUDIT_TYPE,
      EVENT_TIMESTAMP_UTC,DBUSERNAME,END_USER_NAME,SECURITY_CONTEXT_ID,ACTION_NAME,OBJECT_SCHEMA,OBJECT_NAME,
      RETURN_CODE,UNIFIED_AUDIT_POLICIES,SQL_TEXT,RLS_INFO)
    VALUES (v_key,SYS_CONTEXT('USERENV','DB_UNIQUE_NAME'),r.DBID,r.INSTANCE_ID,r.SESSIONID,r.ENTRY_ID,r.STATEMENT_ID,
      r.EXECUTION_ID,r.SCN,r.AUDIT_TYPE,r.EVENT_TIMESTAMP_UTC,r.DBUSERNAME,r.END_USER_NAME,r.SECURITY_CONTEXT_ID,
      r.ACTION_NAME,r.OBJECT_SCHEMA,r.OBJECT_NAME,r.RETURN_CODE,r.UNIFIED_AUDIT_POLICIES,r.SQL_TEXT,r.RLS_INFO);
    v_added:=v_added+1;
   EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; -- Same complete selected record, never SQL/context alone.
   END;
  END LOOP;
  -- Only our copy is eligible for deletion. 0 means no automatic deletion.
  IF v_days>0 THEN
   DELETE FROM DBC_AUDIT_ARCHIVE WHERE EVENT_TIMESTAMP_UTC<v_to-NUMTODSINTERVAL(v_days,'DAY');
   v_deleted:=SQL%ROWCOUNT;
  END IF;
  UPDATE DBC_AUDIT_ARCHIVE_CONFIG SET LAST_SCAN_TO=v_to,LAST_SUCCESS=SYSTIMESTAMP,
   LAST_ADDED=v_added,LAST_SEEN=v_seen,LAST_DELETED=v_deleted WHERE CONFIG_ID=1;
  COMMIT;
 EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
 END COLLECT;
END DBC_AUDIT_ARCHIVER;
