CREATE TABLE DBC_AUDIT_ARCHIVE_CONFIG (
 CONFIG_ID NUMBER PRIMARY KEY CHECK (CONFIG_ID=1),
 VERSION_TAG VARCHAR2(32) NOT NULL,
 INTERVAL_MINUTES NUMBER NOT NULL CHECK (INTERVAL_MINUTES BETWEEN 5 AND 1440),
 RETENTION_DAYS NUMBER NOT NULL CHECK (RETENTION_DAYS BETWEEN 0 AND 3650),
 LAST_SCAN_TO TIMESTAMP(6),
 LAST_SUCCESS TIMESTAMP(6) WITH TIME ZONE,
 LAST_ADDED NUMBER DEFAULT 0 NOT NULL,
 LAST_SEEN NUMBER DEFAULT 0 NOT NULL,
 LAST_DELETED NUMBER DEFAULT 0 NOT NULL
)
