package com.dbcompanion;

import com.dbcompanion.common.db.*;
import com.dbcompanion.model.*;
import com.dbcompanion.model.Ontology.*;
import com.dbcompanion.repository.*;
import com.dbcompanion.service.*;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.json.JsonMapper;
import static org.assertj.core.api.Assertions.*;

class OntologyTest {
    final JsonMapper json=new JsonMapper();
    Snapshot source(){return new Snapshot("DB_A","Mixed Owner","Order\"테이블","원본",List.of(new ColumnInfo(1,"TENANT_ID","NUMBER","N","tenant"),new ColumnInfo(2,"CUSTOMER_ID","NUMBER","Y","customer"),new ColumnInfo(3,"EMAIL","VARCHAR2(100)","Y","sensitive original")),List.of(new Key("FK Customer","R",List.of("TENANT_ID","CUSTOMER_ID"),"Other","Customers",List.of("TENANT","ID"),"ENABLED","NOT VALIDATED")),"2026-09-19T00:00:00Z");}
    Entry entry(){return new Entry("9007199254740994",1,"497c24e0-3b91-4083-ac24-550eea0a0821","DRAFT","ACTOR","2026-09-19",new Document(1,source(),Ontology.initial(source()),"CATALOG",null));}
    @Test void jsonRoundTripPreservesWholeSourceAndNulls(){var e=entry();assertThat(Ontology.parse(Ontology.json(e.document(),json),json)).isEqualTo(e.document());assertThat(e.document().meaning().description()).isEqualTo("원본");}
    @Test void sourceAndMeaningAreImmutable(){var source=source();assertThatThrownBy(()->source.columns().clear()).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->Ontology.initial(source).columns().clear()).isInstanceOf(UnsupportedOperationException.class);}
    @Test void editCannotInventOrOmitColumnsAndRelationships(){var m=Ontology.initial(source());assertThatThrownBy(()->Ontology.validate(source(),new Meaning("","",Map.of(),m.relations()))).isInstanceOf(Failure.class);assertThatThrownBy(()->Ontology.validate(source(),new Meaning("","",m.columns(),Map.of("NEW","x")))).isInstanceOf(Failure.class);}
    @Test void descriptionAndPrivacyValidationRejectMalformedInput(){var m=Ontology.initial(source());for(String text:List.of("x".repeat(8001),"\0","\uD800"))assertThatThrownBy(()->Ontology.validate(source(),new Meaning("",text,m.columns(),m.relations()))).isInstanceOf(Failure.class);var c=new HashMap<>(m.columns());c.put("EMAIL",new ColumnMeaning("","SAFE"));assertThatThrownBy(()->Ontology.validate(source(),new Meaning("","",c,m.relations()))).isInstanceOf(Failure.class);}
    @Test void sensitiveColumnsAreExcludedBeforeAiTransmission(){var e=entry();var m=e.document().meaning();var c=new HashMap<>(m.columns());c.put("EMAIL",new ColumnMeaning("private meaning","SENSITIVE"));var protectedEntry=new Entry(e.seq(),e.revision(),e.documentId(),e.state(),e.actor(),e.recordedAt(),new Document(1,e.document().source(),new Meaning("","",c,m.relations()),"USER",null));String payload=Ontology.aiSource(protectedEntry,json);assertThat(payload).contains("TENANT_ID","CUSTOMER_ID").doesNotContain("EMAIL","private meaning","sensitive original");assertThatThrownBy(()->Ontology.suggestion(protectedEntry,"{\"concept\":\"c\",\"description\":\"d\",\"columns\":{\"EMAIL\":\"email\"}}",json)).isInstanceOf(Failure.class);}
    @Test void aiSuggestionsAreTextOnlyAndPreserveKeysAndPrivacy(){var value=Ontology.suggestion(entry(),"{\"concept\":\"주문\",\"description\":\"주문 설명\",\"columns\":{\"CUSTOMER_ID\":\"고객 식별자\"}}",json);assertThat(value.concept()).isEqualTo("주문");assertThat(value.columns().get("CUSTOMER_ID")).isEqualTo(new ColumnMeaning("고객 식별자","UNKNOWN"));assertThat(value.relations()).isEqualTo(entry().document().meaning().relations());}
    @Test void aiRejectsCodeFencesUnknownColumnsExtraFieldsAndNonStrings(){for(String value:List.of("```json\n{}\n```","{}","{\"concept\":\"x\",\"description\":\"x\",\"columns\":{\"invented\":\"x\"}}","{\"concept\":\"x\",\"description\":\"x\",\"columns\":{},\"sql\":\"DROP TABLE x\"}","{\"concept\":1,\"description\":\"x\",\"columns\":{}}"))assertThatThrownBy(()->Ontology.suggestion(entry(),value,json)).isInstanceOf(Failure.class);}
    @Test void rdfEscapesLiteralAndIdentifierSyntax(){assertThat(OntologyRdf.literal("한글\n\"quote\"\\\t")).isEqualTo("\"한글\\n\\\"quote\\\"\\\\\\t\"");assertThat(OntologyRdf.part("a/b>#% 한글")).startsWith("a%2Fb%3E%23%25%20");}
    @Test void rdfPreservesCompositeKeyPositionsAndDoesNotClaimInstances(){String ttl=OntologyRdf.render(entry());assertThat(ttl).contains("dbc:TableMetadata","dbc:ColumnMetadata","dbc:ForeignKeyMetadata","dbc:position 1 .","dbc:position 2 .","dbc:targetColumn \"TENANT\"","dbc:targetColumn \"ID\"","NOT VALIDATED","DRAFT","ACTOR").doesNotContain("owl:sameAs","owl:Class","CREATE PROPERTY GRAPH");assertThat(ttl).isEqualTo(OntologyRdf.render(entry()));}
    @Test void persistentDocumentIdentitySeparatesDatabasesAndVersions(){var e=entry();String first=OntologyRdf.render(e);var other=new Entry(e.seq(),2,"250b9c3c-6366-403b-95a8-e64ee2939faf",e.state(),e.actor(),e.recordedAt(),e.document());assertThat(OntologyRdf.render(other)).doesNotContain(e.documentId()).contains("/revision/2");assertThat(first).contains(e.documentId()+"/revision/1");}
    @Test void rdfVersionsDoNotMergeDescriptionsOnTheSameSubject(){var e=entry();var next=new Entry("2",2,e.documentId(),"APPROVED",e.actor(),e.recordedAt(),e.document());assertThat(OntologyRdf.render(e)).contains("/revision/1/table>").doesNotContain("/revision/2/table>");assertThat(OntologyRdf.render(next)).contains("/revision/2/table>").doesNotContain("/revision/1/table>");}
    @Test void sharedAiStateSeparatesPurposeAndRetainsOneUseConsent(){var state=new AiAssistant.State();var selection=new AiAssistant.Selection("APP","PROFILE");state.select(selection);var profile=new AiAssistant.Profile(selection,"oci","model","hash");var now=Instant.now();var preview=state.prepare("APP",profile,"T","{}",false,"ko",now,"ontology");assertThatThrownBy(()->state.consume(preview.token(),true,"APP",now)).isInstanceOf(AiAssistant.Failure.class);assertThat(state.consume(preview.token(),true,"APP",now,"ontology").purpose()).isEqualTo("ontology");state.finish();assertThatThrownBy(()->state.consume(preview.token(),true,"APP",now,"ontology")).isInstanceOf(AiAssistant.Failure.class);}
    @Test void proposalTokenIsVersionBoundOneUseAndExpires(){var state=new State();var proposal=new Suggestion("token","A","T",1,Ontology.initial(source()),"A.P",Instant.now().plusSeconds(60));state.suggest(proposal);assertThatThrownBy(()->state.use("token","A","T",2)).isInstanceOf(Failure.class);assertThatThrownBy(()->state.use("token","A","T",1)).isInstanceOf(Failure.class);state.suggest(new Suggestion("old","A","T",1,proposal.meaning(),"A.P",Instant.EPOCH));assertThatThrownBy(()->state.use("old","A","T",1)).isInstanceOf(Failure.class);}
    @Test void schemaCatalogCacheIsLoginScopedAndRefreshClearsBeforeFailure(){var s=new State();var calls=new AtomicInteger();var data=new Catalog("MISSING",true,List.of(),List.of(),"now");for(int i=0;i<2;i++)s.catalog("A",false,()->{calls.incrementAndGet();return data;});assertThat(calls).hasValue(1);assertThatThrownBy(()->s.catalog("A",true,()->{throw new IllegalStateException();})).isInstanceOf(IllegalStateException.class);s.catalog("A",false,()->{calls.incrementAndGet();return data;});assertThat(calls).hasValue(2);}
    @Test void serviceCacheHitUsesNoPoolAndWrongSchemaFailsBeforeDb(){var ds=new SessionDataSource();var jdbc=new org.springframework.jdbc.core.JdbcTemplate(ds);var metadata=new DatabaseRepository(jdbc);var service=new OntologyService(ds,new OntologyRepository(jdbc,json,metadata,new TableStructureRepository(jdbc)),new AiAssistantRepository(jdbc),null,json);try(var pool=new com.zaxxer.hikari.HikariDataSource();var s=new PoolSession(pool,"LOW",()->{})){s.initialize(new DatabaseSession(new DatabaseInfo("APP","APP","LOW","DB"),List.of("APP","OTHER")));var cached=new Catalog("MISSING",true,List.of(),List.of(),"now");s.metadata().ontology().catalog("APP",false,()->cached);assertThat(service.catalog(s,"APP",false)).isSameAs(cached);assertThatThrownBy(()->service.catalog(s,"OTHER",false)).isInstanceOf(Failure.class);assertThat(pool.getHikariPoolMXBean()).isNull();}}
    @Test void ddlIsOneQuotedTableWithVersionAndRevisionKeys(){String sql=OntologySql.create("a\"b");assertThat(sql).startsWith("CREATE TABLE \"a\"\"b\".\"DBC_ONTOLOGY_CATALOG\"").contains("PAYLOAD CLOB","PAYLOAD IS JSON","UNIQUE (OBJECT_OWNER,OBJECT_NAME,REVISION)","SESSION_USER","GENERATED ALWAYS AS IDENTITY","DBC_ONTOLOGY_V1").doesNotContain("TENANT","CUSTOMER","CREATE TRIGGER","GRANT ");assertThat(OntologyRepository.layout()).hasSize(10);}
    @Test void repositoryOnlyWritesCatalogAndReadsBoundDictionaryMetadata() throws Exception {String code=Files.readString(Path.of("src/main/java/com/dbcompanion/repository/OntologyRepository.java"));assertThat(code).contains("jdbc.execute(OntologySql.create(schema))","INSERT INTO \"+OntologySql.table(schema)","OBJECT_OWNER=? AND OBJECT_NAME=?","FETCH FIRST 11 ROWS ONLY","s.setCharacterStream").doesNotContain("UPDATE ","DELETE FROM","DROP TABLE","DBMS_RANDOM","SAMPLE(","GRANT ","COMMENT ON");String svc=Files.readString(Path.of("src/main/java/com/dbcompanion/service/OntologyService.java"));assertThat(svc).contains("new Document(1,before.document().source()","\"DRAFT\",new Document","profile.equals(ai.profile","finally{assistant.finish();}");}
    @Test void malformedVersionsAndJsonAreRejected(){assertThatThrownBy(()->Ontology.parse("{}",json)).isInstanceOf(Failure.class);assertThatThrownBy(()->Ontology.parse("x".repeat(Ontology.MAX_JSON+1),json)).isInstanceOf(Failure.class);for(String invalid:List.of("-1","0","1 OR 1=1"))assertThatThrownBy(()->Ontology.cursor(invalid)).isInstanceOf(Failure.class);Ontology.cursor("9007199254740994");}
    @Test void bulkCaptureGuardsRejectBeforeOpeningAnyConnection(){
        var ds=new SessionDataSource();var jdbc=new org.springframework.jdbc.core.JdbcTemplate(ds);
        var service=new OntologyService(ds,new OntologyRepository(jdbc,json,new DatabaseRepository(jdbc),new TableStructureRepository(jdbc)),new AiAssistantRepository(jdbc),null,json);
        try(var pool=new com.zaxxer.hikari.HikariDataSource();var s=new PoolSession(pool,"LOW",()->{})){
            s.initialize(new DatabaseSession(new DatabaseInfo("APP","APP","LOW","DB"),List.of("APP","OTHER")));
            assertThatThrownBy(()->service.captureMissing(s,"OTHER","T",true)).isInstanceOf(Failure.class);
            assertThatThrownBy(()->service.captureMissing(s,"APP","T",false)).isInstanceOf(Failure.class);
            assertThatThrownBy(()->service.captureMissing(s,"APP",null,true)).isInstanceOf(Failure.class);
            assertThatThrownBy(()->service.captureMissing(s,"APP",OntologySql.TABLE,true)).isInstanceOf(Failure.class);
            assertThat(pool.getHikariPoolMXBean()).isNull();
        }
    }
    @Test void bulkCaptureReusesSnapshotAndAppendsOnlyWhenMissing() throws Exception {
        String code=Files.readString(Path.of("src/main/java/com/dbcompanion/service/OntologyService.java"));
        assertThat(code).contains("if(!exists)saved=appendCapture(s,schema,table)",
                "OntologyRdf.export(saved).triples().size()", "exists?\"SKIPPED\":\"IMPORTED\"",
                "repository.require(schema,login(s))", "finally{s.metadata().ontology().clear(schema);}");
    }
}
