package com.dbcompanion;

import static org.assertj.core.api.Assertions.*;
import com.dbcompanion.model.*;
import java.time.Instant;
import org.junit.jupiter.api.Test;

class SelectAiComparisonTest {
    private final AiAssistant.Profile a=new AiAssistant.Profile(new AiAssistant.Selection("APP","A"),"P","M","1");
    private final AiAssistant.Profile b=new AiAssistant.Profile(new AiAssistant.Selection("APP","B"),"P","M","1");
    private SelectAiComparison.Plan prepare(SelectAiComparison.State state,String question){return state.prepare(a,b,question,"ko",Instant.now());}
    @Test void eachSideHasIndependentTokenConsentAndResultSlot(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");assertThat(plan.baseCalls()).isEqualTo(2);assertThat(plan.showPromptCalls()).isZero();assertThatThrownBy(()->state.consume(plan.left().token(),false,Instant.now())).isInstanceOf(AiAssistant.Failure.class);var left=state.consume(plan.left().token(),true,Instant.now());state.finish(left.token(),new SelectAiTest.Outcome("l",SelectAiTest.Action.SQL,a,"q",Instant.now(),1,"SELECT 1 FROM DUAL",null,null,"complete"));assertThat(state.result().left().id()).isEqualTo("l");assertThat(state.result().rightInspection()).isNull();assertThat(state.result().right()).isNull();assertThat(state.consume(plan.right().token(),true,Instant.now()).profile()).isEqualTo(b);}
    @Test void sameProfileAndConsumedTokenAreRejected(){var state=new SelectAiComparison.State();assertThatThrownBy(()->state.prepare(a,a,"q","ko",Instant.now())).isInstanceOf(AiAssistant.Failure.class);var plan=prepare(state,"q");state.consume(plan.left().token(),true,Instant.now());assertThatThrownBy(()->state.consume(plan.left().token(),true,Instant.now())).isInstanceOf(AiAssistant.Failure.class);}
    @Test void reprepareAndLateAiCompletionAreBlocked(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");state.consume(plan.left().token(),true,Instant.now());assertThatThrownBy(()->prepare(state,"new")).isInstanceOf(AiAssistant.Failure.class);state.finish(plan.left().token(),new SelectAiTest.Outcome("l",SelectAiTest.Action.SQL,a,"q",Instant.now(),1,"SELECT 1 FROM DUAL",null,null,"complete"));state.consume(plan.right().token(),true,Instant.now());state.finish(plan.right().token(),new SelectAiTest.Outcome("r",SelectAiTest.Action.SQL,b,"q",Instant.now(),1,"SELECT 2 FROM DUAL",null,null,"complete"));var ai=state.prepareAi(a,java.util.Set.of("sql"),Instant.now());state.consumeAi(ai.token(),true,Instant.now());assertThatThrownBy(()->prepare(state,"new")).isInstanceOf(AiAssistant.Failure.class);state.finishAi(ai.generation(),ai.token(),"review");var next=prepare(state,"new");assertThatThrownBy(()->state.finishAi(ai.generation(),ai.token(),"late")).isInstanceOf(AiAssistant.Failure.class);assertThat(next.generation()).isNotEqualTo(ai.generation());}
    @Test void detachedInspectionAndShowPromptArePerSideAndRequireConsent(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");var inspection=state.beginInspection("left",null);assertThat(inspection.profile()).isEqualTo(a);assertThatThrownBy(()->prepare(state,"new")).isInstanceOf(AiAssistant.Failure.class);var snap=SelectAiInspection.create(a,"q",java.util.List.of(),Instant.now());state.finishInspection(inspection.generation(),"left",snap);assertThat(state.result().leftInspection()).isEqualTo(snap);var prompts=state.prepareShowPrompt("ko",Instant.now());assertThatThrownBy(()->state.consumePrompt(prompts.left().token(),false,Instant.now())).isInstanceOf(AiAssistant.Failure.class);var left=state.consumePrompt(prompts.left().token(),true,Instant.now());state.finishPrompt(left.token(),new SelectAiTest.Outcome("p",SelectAiTest.Action.PROMPT,a,"q",Instant.now(),1,"actual prompt",null,null,"showprompt"));assertThat(state.result().leftPrompt().text()).isEqualTo("actual prompt");assertThat(state.result().rightPrompt()).isNull();}
    @Test void selectedSaveFreezesExactSideAndObservedSnapshots(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");var left=state.consume(plan.left().token(),true,Instant.now());state.finish(left.token(),new SelectAiTest.Outcome("l",SelectAiTest.Action.SQL,a,"q",Instant.now(),1,"SELECT 1 FROM DUAL",null,null,"complete"));var old=SelectAiInspection.create(a,"q",java.util.List.of(new AiProfileAttribute("comments","old")),Instant.EPOCH);var read=state.beginInspection("left",null);state.finishInspection(read.generation(),"left",old);var save=state.prepareSave(plan.generation(),"left","l",Instant.now());var reread=state.beginInspection("left",old.id());var newer=SelectAiInspection.create(a,"q",java.util.List.of(new AiProfileAttribute("comments","new")),Instant.now());state.finishInspection(reread.generation(),"left",newer);var begin=state.beginSave(plan.generation(),"left","l",save.token(),"parent",Instant.now());assertThat(begin.selection().inspection()).isEqualTo(old);state.finishSave(save.token(),"attempt");assertThat(state.beginSave(plan.generation(),"left","l",save.token(),"parent",Instant.now()).savedId()).isEqualTo("attempt");}
    @Test void oldGenerationWrongSideAndUnconfirmedSaveCannotBeBypassed(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");var left=state.consume(plan.left().token(),true,Instant.now());state.finish(left.token(),new SelectAiTest.Outcome("l",SelectAiTest.Action.SQL,a,"q",Instant.now(),1,null,"failure","ORA-20400","generate"));var save=state.prepareSave(plan.generation(),"left","l",Instant.now());state.beginSave(plan.generation(),"left","l",save.token(),"parent",Instant.now());state.unconfirmedSave(save.token());assertThatThrownBy(()->state.prepareSave(plan.generation(),"left","l",Instant.now())).isInstanceOf(AiAssistant.Failure.class);var next=prepare(state,"next");assertThatThrownBy(()->state.prepareSave(plan.generation(),"left","l",Instant.now())).isInstanceOf(AiAssistant.Failure.class);assertThat(next.generation()).isNotEqualTo(plan.generation());}
    @Test void sideSwitchKeepsSavingLedgerAndBlocksConcurrentReprepare(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");for(var side:java.util.List.of(plan.left(),plan.right())){var value=state.consume(side.token(),true,Instant.now());state.finish(value.token(),new SelectAiTest.Outcome(side==plan.left()?"l":"r",SelectAiTest.Action.SQL,value.profile(),"q",Instant.now(),1,"SELECT 1 FROM DUAL",null,null,"complete"));}var left=state.prepareSave(plan.generation(),"left","l",Instant.now());state.beginSave(plan.generation(),"left","l",left.token(),"parent-a",Instant.now());var right=state.prepareSave(plan.generation(),"right","r",Instant.now());assertThat(right.side()).isEqualTo("right");assertThatThrownBy(()->prepare(state,"new")).isInstanceOf(AiAssistant.Failure.class);state.finishSave(left.token(),"attempt-a");assertThat(state.beginSave(plan.generation(),"left","l",left.token(),"parent-a",Instant.now()).savedId()).isEqualTo("attempt-a");}
    @Test void expiredUnusedOrKnownPrewriteFailureGetsANewReviewToken(){var state=new SelectAiComparison.State();var plan=prepare(state,"q");var left=state.consume(plan.left().token(),true,Instant.now());state.finish(left.token(),new SelectAiTest.Outcome("l",SelectAiTest.Action.SQL,a,"q",Instant.now(),1,"SELECT 1 FROM DUAL",null,null,"complete"));var first=state.prepareSave(plan.generation(),"left","l",Instant.EPOCH);var replacement=state.prepareSave(plan.generation(),"left","l",Instant.EPOCH.plusSeconds(301));assertThat(replacement.token()).isNotEqualTo(first.token());state.beginSave(plan.generation(),"left","l",replacement.token(),"parent",Instant.EPOCH.plusSeconds(301));state.abortSave(replacement.token());assertThat(state.prepareSave(plan.generation(),"left","l",Instant.EPOCH.plusSeconds(302)).token()).isNotEqualTo(replacement.token());}
}
