WITH selected AS (
  SELECT SEQ, OBJECT_OWNER, OBJECT_NAME, REVISION, PAYLOAD
  FROM @@CATALOG@@ WHERE OBJECT_OWNER=@@OWNER@@ AND SEQ IN (@@SEQS@@)
)
SELECT CAST('O:'||TO_CHAR(c.SEQ) AS VARCHAR2(160)) AS NODE_ID,
       CAST('OBJECT' AS VARCHAR2(16)) AS NODE_KIND,
       c.OBJECT_OWNER AS OWNER_NAME, c.OBJECT_NAME,
       CAST(NULL AS VARCHAR2(128)) AS COLUMN_NAME,
       CAST(NULL AS VARCHAR2(256)) AS DATA_TYPE, c.REVISION
FROM selected c
UNION ALL
SELECT CAST('C:'||TO_CHAR(c.SEQ)||':'||TO_CHAR(j.col_pos) AS VARCHAR2(160)),
       CAST('COLUMN' AS VARCHAR2(16)), c.OBJECT_OWNER, c.OBJECT_NAME,
       j.col_name, j.data_type, c.REVISION
FROM selected c,
     JSON_TABLE(c.PAYLOAD, '$.source.columns[*]' ERROR ON ERROR COLUMNS (
       col_pos FOR ORDINALITY,
       col_name VARCHAR2(128) PATH '$.name' ERROR ON ERROR,
       data_type VARCHAR2(256) PATH '$.dataType' ERROR ON ERROR
     )) j
