package com.dbcompanion.common.db;

public final class OntologySql {
    private OntologySql(){}
    public static final String TABLE="DBC_ONTOLOGY_CATALOG";
    public static String table(String schema){return ProfileHistorySql.object(schema,TABLE);}
    public static String create(String schema){return "CREATE TABLE "+table(schema)+"""
        (SEQ NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
         FORMAT_VERSION NUMBER DEFAULT 1 NOT NULL CONSTRAINT DBC_ONTOLOGY_V1 CHECK (FORMAT_VERSION=1),
         OBJECT_OWNER VARCHAR2(128 CHAR) NOT NULL, OBJECT_NAME VARCHAR2(128 CHAR) NOT NULL,
         REVISION NUMBER NOT NULL CHECK (REVISION>=1), DOCUMENT_ID VARCHAR2(36 CHAR) NOT NULL,
         STATE VARCHAR2(12 CHAR) NOT NULL CHECK (STATE IN ('DRAFT','APPROVED')),
         ACTOR VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
         RECORDED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
         PAYLOAD CLOB NOT NULL CHECK (PAYLOAD IS JSON), UNIQUE (OBJECT_OWNER,OBJECT_NAME,REVISION))
        """;}
}
